import { useEffect, useState } from "react";

interface AiEvent {
  id: string;
  eventType: string;
  description: string;
  data: string;
  createdAt: string;
}

const eventColors: Record<string, string> = {
  EMERGENCY_FREEZE: "var(--red)",
  EMERGENCY_FREEZE_AUTO: "var(--red)",
  MONITOR_ERROR: "var(--red)",
  WARNING: "var(--yellow)",
  TG_FREEZE: "var(--red)",
  MONITOR_CYCLE: "var(--muted)",
  MONITOR_IDLE: "var(--muted)",
  AI_ANALYSIS_RUN: "var(--purple)",
  NEURAL_COMMAND: "var(--accent)",
  TG_STATUS_CHECK: "var(--muted)",
  TG_AI_ANALYSIS: "var(--purple)",
  TG_UNFREEZE: "var(--green)",
  TG_ENTROPY_ADJ: "var(--accent)",
  TG_TEST: "var(--muted)",
  MINT: "var(--green)",
  STAKE: "var(--green)",
  UNSTAKE: "var(--yellow)",
};

const eventIcons: Record<string, string> = {
  EMERGENCY_FREEZE: "🔴",
  EMERGENCY_FREEZE_AUTO: "🔴",
  MONITOR_ERROR: "❌",
  MONITOR_CYCLE: "🔄",
  MONITOR_IDLE: "⏸",
  AI_ANALYSIS_RUN: "🧠",
  NEURAL_COMMAND: "⚡",
  TG_STATUS_CHECK: "📊",
  TG_AI_ANALYSIS: "🧠",
  TG_FREEZE: "🔴",
  TG_UNFREEZE: "🟢",
  TG_ENTROPY_ADJ: "⚙️",
  TG_TEST: "📨",
  MINT: "🪙",
  STAKE: "🔒",
  UNSTAKE: "🔓",
};

export function AiEventsLog() {
  const [events, setEvents] = useState<AiEvent[]>([]);
  const [loading, setLoading] = useState(true);

  const load = async () => {
    setLoading(true);
    try {
      const r = await fetch("/api/admin/ai-events", { credentials: "include" });
      if (r.ok) setEvents(await r.json());
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    const interval = setInterval(load, 30000);
    return () => clearInterval(interval);
  }, []);

  const fmt = (iso: string) => {
    const d = new Date(iso);
    return d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" });
  };

  return (
    <div style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 10, padding: 20 }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ fontSize: 18 }}>📡</span>
          <h3 style={{ fontSize: 15, fontWeight: 600 }}>AI Event Stream</h3>
        </div>
        <button
          onClick={load}
          style={{
            background: "transparent", border: "1px solid var(--border)",
            color: "var(--muted)", padding: "4px 10px", borderRadius: 6, fontSize: 12, cursor: "pointer",
          }}
        >
          ⟳ Refresh
        </button>
      </div>

      <div style={{ height: 260, overflowY: "auto", display: "flex", flexDirection: "column", gap: 1 }}>
        {loading ? (
          <div style={{ color: "var(--muted)", fontSize: 12, textAlign: "center", padding: 24 }}>Loading events...</div>
        ) : events.length === 0 ? (
          <div style={{ color: "var(--muted)", fontSize: 12, textAlign: "center", padding: 24 }}>
            No AI events yet. Events are generated by the monitor and admin actions.
          </div>
        ) : (
          events.map((ev) => (
            <div
              key={ev.id}
              style={{
                display: "flex", alignItems: "flex-start", gap: 10,
                padding: "7px 6px", borderBottom: "1px solid var(--border)",
              }}
            >
              <span style={{ fontSize: 13, flexShrink: 0, marginTop: 1 }}>
                {eventIcons[ev.eventType] || "•"}
              </span>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 2 }}>
                  <span style={{
                    fontSize: 10, fontWeight: 700, letterSpacing: "0.5px",
                    color: eventColors[ev.eventType] || "var(--muted)",
                  }}>
                    {ev.eventType}
                  </span>
                  <span style={{ fontSize: 10, color: "var(--muted)", flexShrink: 0, marginLeft: 8 }}>
                    {fmt(ev.createdAt)}
                  </span>
                </div>
                <div style={{ fontSize: 12, color: "var(--text)", lineHeight: 1.4, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                  {ev.description}
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
